export const DATA_PRIVACY_AGREEMENT_VERSION = "v2";

export const DATA_PRIVACY_NOTICE_TITLE = "TLMS Privacy Notice and Consent";

export type PrivacyNoticeSection = {
  title: string;
  paragraphs: readonly string[];
  items?: readonly string[];
};

export const dataPrivacyAgreementSections: readonly PrivacyNoticeSection[] = [
  {
    title: "Scope and transparency",
    paragraphs: [
      "This notice explains how personal data submitted to and generated by the TICAP Logistics Management System (TLMS) portal is handled. It applies to this portal and does not replace any broader, institution-approved privacy notice or policy.",
      "TLMS is designed around the principles of transparency, legitimate purpose, and proportionality. The portal requests information needed for account administration and logistics operations and should not be used to submit unrelated sensitive information.",
    ],
  },
  {
    title: "Personal data processed",
    paragraphs: [
      "Depending on how you use TLMS, the portal may process the following categories of information:",
    ],
    items: [
      "Identity and contact details, including your name, verified email address, and contact number.",
      "Academic and thesis-group details needed to coordinate photoshoot appointments.",
      "Appointment preferences, accessibility requirements, scheduling concerns, attendance, and booking history.",
      "Account, notification, security, and audit records generated through portal use.",
    ],
  },
  {
    title: "Sources and collection",
    paragraphs: [
      "Information is collected directly from forms you submit, from records created when you use portal functions, and from the configured authentication provider when it verifies your identity and email address.",
      "The current portal does not implement direct-marketing or automated-profiling features.",
    ],
  },
  {
    title: "Purposes of processing",
    paragraphs: [
      "TLMS processes personal data only for declared portal and logistics purposes, including:",
    ],
    items: [
      "Creating, verifying, securing, and supporting user accounts.",
      "Managing thesis groups, photoshoot appointments, rescheduling, cancellation, and attendance.",
      "Sending service confirmations, reminders, and operational announcements.",
      "Authorizing staff access, preventing misuse, resolving concerns, and preserving accountable audit records.",
      "Producing authorized operational reports with role-appropriate fields.",
    ],
  },
  {
    title: "Consent and service-related processing",
    paragraphs: [
      "By accepting this notice, you consent to the collection and use of your personal data for the TLMS purposes described here. Information that is necessary to provide a requested service, protect the portal, preserve operational evidence, or meet applicable requirements may still need to be processed consistently with approved institutional policy and law.",
      "You may withhold consent by not creating an account. Withdrawing consent later may limit or prevent continued use of services that require the affected information.",
    ],
  },
  {
    title: "Authorized access and service providers",
    paragraphs: [
      "Access is limited according to assigned roles and operational responsibilities. Students can access their own permitted records; authorized staff can access records required for their duties; and superadministrators can perform restricted security and administration functions.",
      "Configured authentication, database, hosting, and email providers may process the minimum information necessary to operate TLMS. Personal information is not intentionally published through public schedules or public booking references.",
    ],
  },
  {
    title: "Retention and disposal",
    paragraphs: [
      "Personal data should be retained only for as long as necessary for the declared operational, security, audit, and applicable institutional or legal purposes. Records should be securely deleted, anonymized, or otherwise disposed of when continued retention is no longer authorized or necessary.",
      "An exact institutional retention schedule is not stated in this portal notice and must be established through an approved TICAP or institutional policy.",
    ],
  },
  {
    title: "Privacy and security safeguards",
    paragraphs: [
      "TLMS uses verified authentication, server-side authorization, role and resource checks, validation, restricted exports, transactional booking controls, and audit records to reduce unauthorized access or alteration.",
      "No online service can guarantee absolute security. Users must protect their credentials and should never share passwords, verification links, or authentication tokens.",
    ],
  },
  {
    title: "Your data-subject rights",
    paragraphs: [
      "Subject to applicable conditions under Philippine data-privacy rules, data subjects may exercise the following rights:",
    ],
    items: [
      "To be informed about the processing of personal data.",
      "To request access to and correction of personal data.",
      "To object to processing or request erasure or blocking where applicable.",
      "To data portability where applicable.",
      "To file a complaint and seek damages when provided by law.",
    ],
  },
  {
    title: "Requests, corrections, and concerns",
    paragraphs: [
      "Use a verified TICAP channel to request access or correction, withdraw consent, object to processing, or raise a privacy concern. Identity verification may be required before a request affecting protected records is fulfilled.",
      "Withdrawing consent does not automatically remove records that must remain available for an authorized operational, security, audit, institutional, or legal purpose.",
    ],
  },
  {
    title: "Notice updates",
    paragraphs: [
      "This notice may be revised when TLMS functions or approved privacy practices change. The version shown with the notice identifies the text accepted during account creation. A material future change may require a separate review and consent process.",
    ],
  },
];
